config/routes.rb
Rails.application.routes.draw do
  # get "rockets/:id", to "rockets#show"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "rockets#index"
  # get "rockets/:id", to "rockets#show"

  resources :rockets do
    resources :books, only: [:create]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/myposts", to: "rockets#myposts"
  get "/create", to: "rockets#new"
  get "/mybookings", to: "books#mybookings"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  belongs_to :rocket
end

app/models/rocket.rb
class Rocket < ApplicationRecord
  belongs_to :user
  validates :name, :town, :capacity, :price, presence: true # :country à ajouter
  has_one_attached :photo
  has_many :books
  geocoded_by :town
  after_validation :geocode, if: :will_save_change_to_town?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def create
    @book = Book.new(book_params)
    @rocket = Rocket.find(params[:rocket_id])
    @book.rocket = @rocket
    @book.user = current_user
    if @book.save
      redirect_to mybookings_path
    else
      redirect_to rocket_path(@rocket)
    end
  end

  def mybookings
    @user = current_user
    @books = @user.books
  end

  private

  def book_params
    params.require(:book).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def notice
  end
end

app/controllers/rockets_controller.rb
class RocketsController < ApplicationController

  def show
    @rocket = Rocket.find(params[:id])
    @book = Book.new()
    @markers =
    [
      {
        lat: @rocket.geocode[0],
        lng: @rocket.geocode[1]
      }
    ]
  end

  def myposts
    @rockets = Rocket.where(user: current_user)
  end

  def new
    @rocket = Rocket.new
  end

  def create
    @rocket = Rocket.new(rocket_params)
    @rocket.user = current_user
    if @rocket.save
      redirect_to myposts_path(@rocket)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    if params[:query].present?
      sql_query = "country ILIKE :query OR town ILIKE :query"
      @rockets = Rocket.where(sql_query, query: "%#{params[:query]}%")
    else
      @rockets = Rocket.all
    end
  end

  def edit
    @rocket = Rocket.find(params[:id])
  end

  def update
    @rocket = Rocket.find(params[:id])
    @rocket.update(rocket_params)
    redirect_to myposts_path(@rocket)
  end

  def destroy
    @rocket = Rocket.find(params[:id])
    @rocket.destroy
    redirect_to myposts_path, status: :see_other
  end

  private

  def rocket_params
    params.require(:rocket).permit(:name, :photo, :capacity, :country, :town, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/create.html.erb
<div>

  <div class="container-post">
    <h1 class="title-white">My Bookings</h1>
  </div>

  <div>
      <% @books.each do |book| %>
        <div class="card-post">
          <%# <% if rocket.photo.attached? %>
            <%# <%= cl_image_tag rocket.photo.key, height: 180, width: 230, crop: :fill %>
            <%# <% else %>
            <%# <%= image_tag("Fusée1.png", class:"image-placeholder") %>
          <%# <% end %>
          <div class="card-inpost">
            <p> <%= book.start_date %></p>
            <p> <%= book.end_date %></p>
            <p><%= @rocket.name %></p>
            <p><%= @rocket.capacity %></p>
            <p><%= @rocket.price%></p>
            <p><%= @rocket.town %></p>
          </div>
        </div>
      <% end %>

  </div>

</div>

app/views/books/mybookings.html.erb
<div>

  <div class="container-title">
    <h1 class="title-white">My Reservations</h1>
  </div>

  <div>
      <% @books.each do |book| %>
        <div class="card-booking">
          <div>
          <p class="title-blue"><%= book.rocket.name %></p>
            <div class="content-text">
              <div>

                  <p class="text-blue">Departure : </p>
                  <p class="text-blue">Arrival   : </p>
                  <p class="text-blue">City      : </p>
                  <p class="text-blue">Capacity  : </p>
                  <p class="text-blue">Price     : </p>
              </div>
              <div>
                <p class="text-blue"> <%= book.start_date %></p>
                <p class="text-blue"> <%= book.end_date %></p>
                <p class="text-blue"> <%= book.rocket.town %></p>
                <p class="text-blue"> <%= book.rocket.capacity %></p>
                <p class="text-blue"> <%= book.rocket.price%></p>
              </div>
             </div>
              <% if book.rocket.photo.attached? %>
          </div>
          <div>
              <%= cl_image_tag (book.rocket.photo.key), height: 280, width: 310 %>
              <% end %>
          </div>
        </div>
      <% end %>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crazy_Rockets</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="/assets/application.css?body=1" rel="stylesheet" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/rockets/destroy.html.erb
<div class="container-white-2">
    <%= simple_form_for @rocket do |f| %>
      <%= f.input :name %>
      <%= f.input :photo, as: :file %>
      <%= f.input :capacity %>
      <%# <%= f.input :country %>
      <%= f.input :town %>
      <%= f.input :price %>
      <%= f.submit "Delete", class:"btn-red-2" %>
    <% end %>
</div>

app/views/rockets/edit.html.erb
<div class="container-white-2">
    <%= simple_form_for @rocket do |f| %>
      <%= f.input :name %>
      <%= f.input :photo, as: :file %>
      <%= f.input :capacity %>
      <%# <%= f.input :country %>
      <%= f.input :town %>
      <%= f.input :price %>
      <%= f.submit "Update", class:"btn-red-2" %>
    <% end %>
</div>

app/views/rockets/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/rockets/index.html.erb
<div class="container">
  <%= form_with url: rockets_path, method: :get, class: "d-flex" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Enter a country or a town"
  %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>
</div>

<div class="container">
  <div class="row row-cols-1 row-cols-md-3 g-4" id="container">
    <% @rockets.each do |rocket| %>
      <%= link_to rocket_path(rocket) do %>
        <div class="col">
          <div class="card">
            <div class="body-card">
              <% if rocket.photo.attached? %>
                <%= cl_image_tag rocket.photo.key, height: 150, width: 290 , crop: :fill %>
              <h5 class="rocket-name"><%= rocket.name %></h5>
              <p class="card-text-style">Price: <%= rocket.price %>per day.</p>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<div class="footer">
</div>

app/views/rockets/myposts.html.erb
<div>

  <div class="container-title">
  <h1 class="title-white">My posts</h1>

  <%# <%= link_to "Create", new_rocket_path, class:"btn-red-2" %>
  </div>

  <div class="column2">
      <% @rockets.each do |rocket| %>
        <div class="card-post">
          <% if rocket.photo.attached? %>
            <%= cl_image_tag rocket.photo.key, height: 180, width: 230, crop: :fill %>
            <% else %>
            <%= image_tag("Fusée1.png", class:"image-placeholder") %>
          <% end %>
          <div class="card-text">
            <h3 class="title-blue"><%= link_to rocket.name, rocket_path(rocket) %></h3>
            <%= link_to "Update", edit_rocket_path(rocket), class:"btn-red-2" %>
            <%= link_to "Delete", rocket_path(rocket), data: {turbo_method: :delete}, class:"btn-red-2" %>
          </div>
        </div>
      <% end %>

  </div>

</div>

app/views/rockets/new.html.erb
<div class="container-white-2">
      <%= simple_form_for @rocket do |f| %>
        <%= f.input :name, input_html: {class:"form-design form-text"} %>
        <%= f.input :photo, as: :file, input_html: {class:"form-design form-text"} %>
        <%= f.input :capacity, input_html: {class:"form-design form-text"} %>
        <%# <%= f.input :country %>
        <%= f.input :town, input_html: {class:"form-design form-text"} %>
        <%= f.input :price, input_html: {class:"form-design form-text"} %>
        <%= f.submit "Create", class:"btn-red-2" %>
      <% end %>
</div>

app/views/rockets/show.html.erb
<div class="container-white-2">
  <div>
    <h1>Rocket name</h1>
    <p class="font"><%= @rocket.name %></p>
    <h2>Owner</h2>
    <p class="font"><%= @rocket.user.name %></p>
  </div>

  <div class="rocket-show-card-top">
    <div>
      <h2>Capacity:</h2>
      <p class="font"><%= @rocket.capacity %></p>
      <h2>Price:</h2>
      <p class="font"><%= @rocket.price %></p>
    </div>
      <%# <%= image_tag "Fusée5.png", alt: "Fusee5", width: 200 %>
      <% if @rocket.photo.attached? %>
        <%= cl_image_tag @rocket.photo.key, height: 200, width: 200, crop: :fill %>
      <% end %>
  </div>


  <div class="rocket-show-card-top">
    <div>
      <a href="app/assets/images/map.png"></a>
      <div class="">
        <h2>City </h2>
        <p class="font"><%= @rocket.town %></p>
      </div>
    </div>
  </div>

    <div style="width: 98%; height: 200px;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>

  <div class="rocket-show-card-button">
  <%= simple_form_for([@rocket, @book]) do |f| %>
    <%= f.input :start_date, input_html: {class:"form-design form-text"} %>
    <%= f.input :end_date, input_html: {class:"form-design form-text"} %>
  <%= f.submit "Book", class:"btn-red-2" %>
      <% end %>
  </div>
  <div class="footer">
  </div>


</div>

app/views/shared/_navbar.html.erb
  <div class="navbar_custom">


    <ul class="list_inline">

      <li class="list_inline" id="img">
        <%= image_tag("rocket_logo.png") %>
      </li>

      <%= link_to root_path do %>
        Home
      <% end %>

      <li class="list_inline"><a href=""></a>
      </li>

      <%= link_to mybookings_path do %>
        My Reservations
      <% end %>

      <%= link_to myposts_path do %>
        My Posts
      <% end %>

      <%= link_to create_path do %>
        Create a Post
      <% end %>

      <%= link_to user_session_path do %>
        Log-in
      <% end %>
      <%= link_to destroy_user_session_path, data: {turbo_method: :delete} do %>
        Log-out
      <% end %>
    </ul>


  </div>